# Generated by Django 4.1.3 on 2022-11-15 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('menu', models.CharField(choices=[('Первые блюда', 'Первые блюда'), ('Вторые блюда', 'Вторые блюда'), ('Десерты', 'Десерты'), ('Винная карта', 'Винная карта'), ('Бар', 'Бар')], max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
