# Generated by Django 4.1.3 on 2022-12-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu',
            field=models.CharField(choices=[('Первые блюда', 'Первые блюда'), ('Вторые блюда', 'Вторые блюда'), ('Десерты', 'Десерты'), ('Винная карта', 'Винная карта'), ('Напитки', 'Напитки')], max_length=100),
        ),
    ]
