# Generated by Django 4.1.3 on 2022-12-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home_page", "0002_alter_menu_menu"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("phone_number", models.CharField(max_length=40, null=True)),
                ("date", models.DateField()),
                ("guests_num", models.IntegerField()),
                (
                    "branch",
                    models.CharField(
                        choices=[
                            ("Асанбай", "Асанбай"),
                            ("Белый Аист", "Белый Аист"),
                            ("Токтогула", "Токтогула"),
                            ("Шопокова", "Шопокова"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
        ),
    ]
