# Generated by Django 4.1.3 on 2022-12-19 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home_page", "0003_booking"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="guests_num",
            new_name="guests",
        ),
        migrations.RenameField(
            model_name="booking",
            old_name="phone_number",
            new_name="phone",
        ),
    ]
