# Generated by Django 4.1.3 on 2022-11-16 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0003_news_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.CharField(max_length=50, null=True)),
                ('whatsApp', models.CharField(max_length=40, null=True)),
                ('telegram', models.TextField(null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('address', models.TextField(null=True)),
                ('adress_map', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
