# Generated by Django 4.1.3 on 2022-11-16 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0004_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='adress_map',
            new_name='address_map',
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
