# Generated by Django 4.1.4 on 2022-12-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0005_alter_menu_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='branch',
            field=models.CharField(choices=[('Asanbai', 'Asanbai'), ('Golden Stork', 'Golden Stork'), ('Toktogula', 'Toktogula'), ('Shopokova', 'Shopokova')], max_length=100),
        ),
    ]
